# Generated by Django 2.2.5 on 2019-12-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191218_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
