# Generated by Django 3.0 on 2019-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191218_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
    ]
